version: "3.7"
services:
  influxdb:
    image: influxdb:1.7.3-alpine
    container_name: openstf-influxdb
    volumes:
      - ./influxdb:/docker-entrypoint-initdb.d
    ports:
      - 8086:8086
  mysql:
    image: mysql:5.7
    container_name: openstf-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: openstf-phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
  grafana:
    image: grafana/grafana:7.5.1
    container_name: openstf-grafana
    # volumes:
    # ${DOCKER_HOME}/grafana/volume/data:/var/lib/grafana
    ports:
      - 3000:3000
  grafana-configurator:
    image: alpine:3.7
    container_name: openstf-grafana-configurator
    depends_on:
      - "grafana"
    command: ["/opt/grafana-configurator/wait-for", "grafana:3000", "--", "sh", "/opt/grafana-configurator/example_data/run_this_to_copy.sh"]
    volumes:
      - ./grafana-configurator:/opt/grafana-configurator
