version: "3.7"
services:
  influxdb:
    image: influxdb:1.7.3-alpine
    container_name: openstf-influxdb
    volumes:
      - ./influxdb/volume/initdb:/docker-entrypoint-initdb.d
    environment:
      FORECAST_DB_NAME: forecast_latest
    ports:
      - 8086:8086
  mysql:
    image: mysql:5.7
    container_name: openstf-mysql
    volumes:
      - ./mysql/volume/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tst_icarus
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: openstf-phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
  grafana:
    image: grafana/grafana:7.5.1
    container_name: openstf-grafana
    # volumes:
    # ${DOCKER_HOME}/grafana/volume/data:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"
  grafana-configurator:
    image: alpine:3.7
    container_name: openstf-grafana-configurator
    depends_on:
      - "grafana"
    command: ["/opt/grafana-configurator/wait-for", "grafana:3000", "--", "sh", "/opt/grafana-configurator/configurator.sh"]
    volumes:
      - ./grafana-configurator:/opt/grafana-configurator
    environment:
      GRAFANA_USER: admin
      GRAFANA_PASSWORD: admin
  nginx:
    image: nginx
    container_name: openstf-nginx
    volumes:
     - ./nginx/volume:/usr/share/nginx/html
    ports:
     - "8090:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
